addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.13.0")
addSbtPlugin("io.stryker-mutator"   % "sbt-stryker4s"         % "0.16.1")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "2.2.0")
addSbtPlugin("com.github.sbt"       % "sbt-release"           % "1.4.0")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"               % "2.2.1")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          % "3.11.3")
