addSbtPlugin("net.aichler"        % "sbt-jupiter-interface" % "0.11.1")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s"         % "0.16.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"         % "2.0.5")
addSbtPlugin("com.github.sbt"     % "sbt-release"           % "1.1.0")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"               % "2.2.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"          % "3.9.21")
